### ISSUE TITLE
add polyte to conda savage package?

### ISSUE THREAD

**Issue by michaelkarlcoleman** [HaploConduct/HaploConduct#1]
Hi,

Unless I'm missing something, it looks like once one has the conda savage package, polyte is just two extra Python scripts.  Seems like it'd be easy and useful to add these to the savage package.

(If you do this, 'scipy' needs to be added as a dep.)

Regards,
Mike

**Comment by jbaaijens** [comment]
Hi Mike,

Thanks for the suggestion, it has been on my list to make polyte available on bioconda but I didn't get to it yet. Rather than adding polyte to the savage package, I would like to have a haploconduct package, so there will be a haploconduct wrapper from which one can run savage and polyte. I'll take care of it asap.

Cheers,
Jasmijn

**Comment by jblamyatifremer** [comment]
Hi, 
+1 from a conda repo of Polyte that seems quite appeal. 
JB

**Comment by jbaaijens** [comment]
HaploConduct is now available through Bioconda, offering both SAVAGE and POLYTE :)
